-- 0009: row-level security.
--
-- RLS is enabled on every table, so nothing is reachable with the public key
-- unless a policy below allows it. The service role bypasses RLS and is used
-- only by server code; it is never shipped to a client.
--
-- Patient data (patient_profile, care_circle, circle_membership, appointment,
-- appointment_event, access_log):
--   * Access by another person goes through has_circle_consent(), which
--     requires the patient's recorded, unrevoked consent. A membership or
--     booked_by relationship alone grants nothing.
--   * There is deliberately NO blanket policy for admin/staff. Internal lookups
--     of patient data go through server endpoints that write to access_log.
--   * There are no client write policies. Writes go through server endpoints
--     (which validate, apply consent rules and log access).

alter table public.app_user enable row level security;
alter table public.location enable row level security;
alter table public.organization enable row level security;
alter table public.facility enable row level security;
alter table public.practitioner enable row level security;
alter table public.practitioner_facility enable row level security;
alter table public.service enable row level security;
alter table public.service_prep enable row level security;
alter table public.price_item enable row level security;
alter table public.coverage_program enable row level security;
alter table public.accreditation enable row level security;
alter table public.patient_profile enable row level security;
alter table public.care_circle enable row level security;
alter table public.circle_membership enable row level security;
alter table public.access_log enable row level security;
alter table public.schedule enable row level security;
alter table public.availability_rule enable row level security;
alter table public.schedule_exception enable row level security;
alter table public.slot enable row level security;
alter table public.appointment enable row level security;
alter table public.appointment_event enable row level security;
alter table public.verification_task enable row level security;
alter table public.data_source_import enable row level security;

-- ---------------------------------------------------------------------------
-- Accounts
-- ---------------------------------------------------------------------------
create policy app_user_select_own_or_staff on public.app_user
  for select to authenticated
  using (id = (select auth.uid()) or (select public.is_staff()));

-- Only admins assign roles or deactivate accounts.
create policy app_user_admin_write on public.app_user
  for all to authenticated
  using ((select public.current_app_role()) = 'admin')
  with check ((select public.current_app_role()) = 'admin');

-- ---------------------------------------------------------------------------
-- Supply, coverage and admin tables: internal team only for now. Doctor and
-- provider-portal policies arrive with those surfaces; public read access
-- arrives with the public website.
-- ---------------------------------------------------------------------------
do $$
declare
  t text;
begin
  foreach t in array array[
    'location', 'organization', 'facility', 'practitioner', 'practitioner_facility',
    'service', 'service_prep', 'price_item', 'coverage_program', 'accreditation',
    'schedule', 'availability_rule', 'schedule_exception',
    'verification_task', 'data_source_import'
  ]
  loop
    execute format(
      'create policy staff_all on public.%I for all to authenticated '
      'using ((select public.is_staff())) with check ((select public.is_staff()))',
      t
    );
  end loop;
end;
$$;

-- A doctor reads their own practitioner row (PRC status is set by admin).
create policy practitioner_select_own on public.practitioner
  for select to authenticated
  using (app_user_id = (select auth.uid()));

-- Slots are generated by the server; nobody posts them, staff included.
create policy slot_staff_select on public.slot
  for select to authenticated
  using ((select public.is_staff()));

-- ---------------------------------------------------------------------------
-- Patient data
-- ---------------------------------------------------------------------------

-- The patient, or a care manager with recorded consent. Payers and viewers get
-- only what the server chooses to send them (receipts, visit updates).
create policy patient_profile_select on public.patient_profile
  for select to authenticated
  using (
    app_user_id = (select auth.uid())
    or public.has_circle_consent(id, array['care_manager']::public.circle_role[])
  );

create policy care_circle_select on public.care_circle
  for select to authenticated
  using (
    public.is_patient_self(patient_id)
    or public.has_circle_consent(
      patient_id, array['care_manager', 'payer', 'viewer']::public.circle_role[]
    )
  );

-- A member sees their own membership (including a pending invitation); the
-- patient sees everyone in their circle.
create policy circle_membership_select on public.circle_membership
  for select to authenticated
  using (
    member_user_id = (select auth.uid())
    or exists (
      select 1 from public.care_circle c
      where c.id = circle_id and public.is_patient_self(c.patient_id)
    )
  );

-- The patient, a consented care manager, or the practitioner the appointment
-- is with. booked_by on its own grants nothing.
create policy appointment_select on public.appointment
  for select to authenticated
  using (
    public.is_patient_self(patient_id)
    or public.has_circle_consent(patient_id, array['care_manager']::public.circle_role[])
    or exists (
      select 1 from public.practitioner p
      where p.id = practitioner_id and p.app_user_id = (select auth.uid())
    )
  );

-- Visible exactly when the appointment is (the subquery runs under the
-- caller's own appointment policy).
create policy appointment_event_select on public.appointment_event
  for select to authenticated
  using (exists (select 1 from public.appointment a where a.id = appointment_id));

-- The patient sees who accessed their data; admins review the log.
create policy access_log_select on public.access_log
  for select to authenticated
  using (
    public.is_patient_self(subject_patient_id)
    or (select public.current_app_role()) = 'admin'
  );
